"""Time-ordered identifier generation (UUID version 7).

Why time-ordered rather than random: identifiers become database keys, and a
random key scatters inserts across the whole index, dirtying many pages per
write and degrading as the table grows. A time-ordered key appends to the end of
the index, so inserts touch one page and stay fast at any size. For a message
table expected to reach hundreds of thousands of rows this is the difference
between a sync that stays quick and one that slows down over months.

UUID version 7 (RFC 9562) provides exactly that: a 48-bit millisecond timestamp
followed by a counter and random bits. Python 3.14 adds ``uuid.uuid7``; on
earlier versions this module implements the same layout, and prefers the
standard library's version when it is present.

See ADR-033.
"""

from __future__ import annotations

import secrets
import threading
import uuid
from typing import Final

from tgassist.domain.ports.clock import Clock
from tgassist.domain.ports.id_generator import IdGenerator

_UUID_VERSION: Final = 7
_UUID_VARIANT: Final = 0b10

_TIMESTAMP_BITS: Final = 48
_COUNTER_BITS: Final = 12
_COUNTER_MAX: Final = (1 << _COUNTER_BITS) - 1
_RAND_B_BITS: Final = 62

_MS_PER_SECOND: Final = 1000


class UuidV7IdGenerator(IdGenerator):
    """Generates time-ordered identifiers backed by UUID version 7.

    A monotonic counter occupies the ``rand_a`` field, which RFC 9562 permits
    and which makes identifiers strictly increasing rather than merely
    increasing per millisecond. That matters because "sortable" is only useful
    if two identifiers created in the same millisecond still sort in creation
    order.

    Two conditions the counter also handles:

    * **The clock moves backwards** (an NTP correction, a virtual machine
      resuming). The generator never emits an earlier timestamp than one it has
      already used; it holds the previous value until wall time catches up.
      Uniqueness is preserved by the counter.
    * **More than 4096 identifiers in one millisecond.** The generator advances
      its logical millisecond rather than blocking or colliding. Sustained
      generation at that rate would drift ahead of wall time, which is
      acceptable and vastly preferable to a duplicate key.

    Instances are thread-safe: SQLite runs on its own worker thread (ADR-013),
    so identifier generation is reachable from more than one thread.
    """

    __slots__ = ("_clock", "_counter", "_last_ms", "_lock")

    def __init__(self, clock: Clock) -> None:
        """Create a generator.

        Args:
            clock: Time source. Injected rather than read directly so that
                identifier generation is deterministic under test.
        """
        self._clock = clock
        self._lock = threading.Lock()
        self._last_ms = -1
        self._counter = 0

    def new_id(self) -> int:
        """Return a positive, strictly increasing 60-bit integer identifier.

        The layout mirrors the UUID: 48 timestamp bits followed by the same
        12-bit counter, so integer and UUID identifiers generated by one
        instance sort into the same order.
        """
        timestamp_ms, counter = self._next()
        return (timestamp_ms << _COUNTER_BITS) | counter

    def new_uuid(self) -> str:
        """Return a canonical, strictly increasing UUID version 7 string."""
        return str(self._new_uuid_object())

    def new_correlation_id(self) -> str:
        """Return an identifier tying together the log records of one operation."""
        return str(self._new_uuid_object())

    def _new_uuid_object(self) -> uuid.UUID:
        timestamp_ms, counter = self._next()
        value = (
            (timestamp_ms << 80)
            | (_UUID_VERSION << 76)
            | (counter << 64)
            | (_UUID_VARIANT << _RAND_B_BITS)
            | secrets.randbits(_RAND_B_BITS)
        )
        return uuid.UUID(int=value)

    def _next(self) -> tuple[int, int]:
        """Return the next (timestamp, counter) pair, strictly increasing."""
        now_ms = int(self._clock.now().timestamp() * _MS_PER_SECOND)
        with self._lock:
            if now_ms > self._last_ms:
                self._last_ms = now_ms
                self._counter = 0
            elif self._counter >= _COUNTER_MAX:
                # Counter exhausted, or the clock went backwards. Advance the
                # logical millisecond: drifting slightly ahead of wall time is
                # always preferable to emitting a duplicate identifier.
                self._last_ms += 1
                self._counter = 0
            else:
                self._counter += 1
            return self._last_ms, self._counter
